### ISSUE TITLE
微信 DecryptOpenDataToStruct 大概率会出现问题

### ISSUE THREAD

**Issue by lujscn** [iGoogle-ink/gopay#102]
不论是解密小程序用户信息还是解密手机号，出现故障的概率非常大，大约有一半的概率。
错误提示如下：

json.Marshal(�o۾[�c����r9*F����2�H��^�fGW����Ǐ�5	��1lP�kz3q_/�j��D��TB�0�JI��
���6yάm���F�% �'[�\o��1lf�e���^��l_YR�6V@�Q1���>VU�%��	D���)：invalid character 'Ù' looking for beginning of value

**Comment by lujscn** [comment]
谢谢大神，本人小白，对底层的东西懂得比较少，
再次研究发现，第一次发生错误的概率大约有八九成，成功的概率一两成，然后继续请求，成功的概率大约八九成。
再贴一点错误信息，希望能对排除错误有所帮助。


DecryptOpenDataToStruct err: json.Marshal(
����~-����8��Ti�k�v w'%Kى;�p���8��?�-C�]GV�3d���6#&�ٳm�cˬl�F���>N�`0�ǲ�7#iű)：invalid character '\u0095' looking for beginning of value
[GVA]2021/02/05 - 16:37:03.241	error	D:/Colin/Projects/gva_dfzrf/server/service/lq_wechat.go:52	微信手机登录失败，请重试	{"err": "json.Marshal(\n\ufffd\u0008\ufffdN\ufffd\ufffdL\ufffd\ufffd\u0013\ufffd\ufffd~\u0003\u000b\ufffd\ufffd\ufffd\"\ufffd\ufffd\ufffd\t\u0016\ufffd\ufffdF\ufffd;\ufffd\ufffd9\ufffd\ufffd\u0014-i\ufffd\ufffdKo}\ufffd\u0016\ufffd\u0017\u000e\ufffd\ufffd,V:\ufffd\ufffd\r\ufffd\u0018\ufffd\ufffd\u0004\u0016\ufffd\ufffd\ufffd\u000b^\ufffdMv\ufffd\r\ufffd\ufffd\ufffd\u0019\u0006\ufffd\ufffd~-\ufffd\ufffd\u0002\ufffd\ufffd8\ufffd\ufffdTi\ufffdk\ufffdv w'%Kى;\ufffdp\ufffd\ufffd\ufffd8\ufffd\ufffd?\ufffd-C\ufffd\u001c]GV\ufffd3d\ufffd\ufffd\ufffd6#&\ufffdٳm\ufffdcˬl\ufffdF\ufffd\u0010\ufffd\ufffd>\u0006\u0006N\ufffd`0\ufffdǲ\ufffd7#iű)：invalid character '\\u0095' looking for beginning of value"}

**Comment by wziww** [comment]
DecryptOpenDataToStruct 方法传入的参数方便提供下么

**Comment by lujscn** [comment]
代码：

fmt.Printf("\n==========wxLoginReq.EncryptedData===========\n%+v\n%[1]T\n",wxLoginReq.EncryptedData)
fmt.Printf("\n==========wxLoginReq.Iv===========\n%+v\n%[1]T\n",wxLoginReq.Iv)
fmt.Printf("\n==========sessionRsp.SessionKey===========\n%+v\n%[1]T\n",sessionRsp.SessionKey)
// 微信小程序 获取手机号
wxPhone = new(wechat.UserPhone)
err = wechat.DecryptOpenDataToStruct(wxLoginReq.EncryptedData, wxLoginReq.Iv, sessionRsp.SessionKey, wxPhone)
if err != nil {
    fmt.Println("DecryptOpenDataToStruct err:", err)
    global.GVA_LOG.Error("微信手机登录失败，请重试", zap.Any("err", err))
    return nil, nil, errors.New("请重试")
}


日志（第一次失败，第二次成功）：
==========wxLoginReq.EncryptedData===========
/m11I5kuo4wnSst2LN34iQTuTmkcKjgqObyaiDnFkb9wU6IMha3f+4nRt4LFJ+N6F3mXvRgQzTBmm5usmcGfeDF/M6TA1n9lhOFRWRDigrMg2mcW+pRNsdBPS161lIf/m/35vSAGPZoX8SHoVebHzkQjzSKRu2oeQk4Z+90iotxyoN9+Rvxyy5wcmKRTeVYXpmbymTrX/LzxfFBDVkctSA==
string

==========wxLoginReq.Iv===========
sIi96rRZasU+nkFsTg2yGA==
string

==========sessionRsp.SessionKey===========
313JQxPLkfYooRk75Q+SjA==
string
DecryptOpenDataToStruct err: json.Marshal(���M�mW���8�{�'�{C��*��&\% ���z/��G��R�f������jr��j�Y�3)�z8&�W���~jeްgc�5F�@%���c:Z�84����dy+�����)���ϻ��q*~�`���#��;:s&����Я1�F�>��t+�=/i�^��)：invalid character '\u009c' looking for beginning of value
[GVA]2021/02/05 - 16:49:35.420	error	D:/Colin/Projects/gva_dfzrf/server/service/lq_wechat.go:55	微信手机登录失败，请重试	{"err": "json.Marshal(\ufffd\ufffd\ufffdM\ufffdmW\ufffd\ufffd\ufffd8\ufffd{\ufffd'\ufffd{C\ufffd\u0004\ufffd*\ufffd\ufffd&\\%\u0003 \u0011\ufffd\ufffd\ufffdz/\ufffd\ufffd\u0016G\u0001\ufffd\ufffdR\ufffdf\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdjr\ufffd\ufffdj\ufffdY\ufffd3)\ufffdz8&\ufffdW\ufffd\ufffd\ufffd~jeްgc\ufffd5F\ufffd@%\u001d\ufffd\ufffd\ufffdc:Z\ufffd84\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdd\u001ey+\u000e\ufffd\ufffd\u0016\ufffd\ufffd\ufffd)\ufffd\ufffd\ufffdϻ\ufffd\ufffdq*~\ufffd`\ufffd\ufffd\ufffd\u0005#\ufffd\ufffd;:s&\ufffd\ufffd\ufffd\u000e\ufffdЯ1\u000c\ufffdF\ufffd>\ufffd\ufffd\u001bt+\ufffd=/i\ufffd^\ufffd\ufffd)：invalid character '\\u009c' looking for beginning of value"}
[GVA]2021/02/05 - 16:49:35.420	error	D:/Colin/Projects/gva_dfzrf/server/api/jst_dfzrf/auth.go:38	手机登录出错!	{"err": "请重试"}
[GIN] 2021/02/05 - 16:49:35 | 200 |    403.4236ms |             ::1 | POST     "/dfzrf/wx-login-mobile"

==========wxLoginReq.EncryptedData===========
o7+z22hedr5RIE3CBhnOl5MA2WGM7nP8WxJ5JcGrVhc28T8KxJ5ELCAwoOa29UzBBBv3ToxgIHJ7Vli4KJBjSuQz0dLqbxhqE73skYVQb8gxJ2kyqwufX+JPJPZcmSmikRJC5XhJYnWZjKhi6XSGsNyhKP4mwa/p4vekp+uOQqhcnhiH3Gwy+Cixj2rXxvpPAFwwSkv/nzctv8UqB4dzDA==
string

==========wxLoginReq.Iv===========
dP+aGnoBB9tCvtNNukrm3w==
string

==========sessionRsp.SessionKey===========
313JQxPLkfYooRk75Q+SjA==
string
[GVA]2021/02/05 - 16:49:44.704	info	D:/Colin/Projects/gva_dfzrf/server/initialize/internal/logger.go:146	gorm	{"src": "D:/Colin/Projects/gva_dfzrf/server/service/lq_users.go:34", "duration": 2.0009, "rows": 1, "sql": "SELECT * FROM `lq_users` WHERE `mobile` = '13913959731' AND `lq_users`.`deleted_at` IS NULL ORDER BY `lq_users`.`id` LIMIT 1"}
[GIN] 2021/02/05 - 16:49:44 | 200 |    280.0439ms |             ::1 | POST     "/dfzrf/wx-login-mobile"

**Comment by lujscn** [comment]
fmt.Printf("\n==========wxLoginReq.EncryptedData\n%+v\n%[1]T\n", wxLoginReq.EncryptedData)
fmt.Printf("\n==========wxLoginReq.Iv\n%+v\n%[1]T\n", wxLoginReq.Iv)
fmt.Printf("\n==========sessionRsp.SessionKey\n%+v\n%[1]T\n", sessionRsp.SessionKey)
// 微信小程序 获取手机号
wxPhone = new(wechat.UserPhone)
err = wechat.DecryptOpenDataToStruct(wxLoginReq.EncryptedData, wxLoginReq.Iv, sessionRsp.SessionKey, wxPhone)
if err != nil {
	fmt.Println("DecryptOpenDataToStruct err:", err)
	global.GVA_LOG.Error("微信手机登录失败，请重试", zap.Any("err", err))
	return nil, nil, errors.New("请重试")
}
fmt.Printf("DecryptOpenDataToStruct:\n%+v\n", *wxPhone)


日志（第一次失败，之后都是成功的）
==========wxLoginReq.EncryptedData
/8qcwESUOOFUibsyQe+fq9cktKd2HhwMav0E6X6QRUNZw9EdAZV21sGJW5WeV20Om+ExaNPgyAwM/7TH/jqx2drAkzrQxLTNPmV7ZHahfBVAtfZmWakxUz/BlTVq1/OkVan87z2sUX87P3Sy+MIwuB6dvvaBKtO9Hdg9CVHMGLd2y3Z2xf5Syl4D1FJEk4X/UM4zowzJT8yR1DWMm0WjuA==
string

==========wxLoginReq.Iv
KOfQ6Cu5Y7ZPikQi/gIp9g==
string

==========sessionRsp.SessionKey
ki65GuRX8eTisqPNenmWKg==
string
DecryptOpenDataToStruct err: json.Marshal(�� ��uv܋%��n6iw۷c��Ι|`����A?٢>��tC"*��^T���Ӝڒ�9��ͯ��l�T����ߚ�B�²bjzS� Lp�(`TՌ���ʩ����O>�&����>�R�Za&�V�_cq���3z�ts����j����#�)：invalid character '\x03' looking for beginning of value
[GVA]2021/02/05 - 16:54:07.467	error	D:/Colin/Projects/gva_dfzrf/server/service/lq_wechat.go:55	微信手机登录失败，请重试	{"err": "json.Marshal(\u0003\ufffd\ufffd\u0000\ufffd\ufffduv܋%\ufffd\ufffd\ufffdn\u000e6\u0016i\u001aw۷c\ufffd\ufffdΙ|`\ufffd\ufffd\ufffd\ufffdA?٢>\ufffd\u001f\ufffdtC\"*\ufffd\ufffd^T\ufffd\ufffd\ufffdӜڒ\ufffd9\ufffd\ufffdͯ\ufffd\ufffd\u000bl\ufffdT\ufffd\u0005\ufffd\ufffd\ufffdߚ\ufffdB\ufffd²\u0019bjzS\ufffd\u0000Lp\ufffd(\u000e`TՌ\ufffd\ufffd\ufffdʩ\ufffd\ufffd\ufffd\ufffdO\u0006>\ufffd&\ufffd\u0013\u001f\ufffd\ufffd\u000b\ufffd\ufffd>\ufffd\ufffd\u0010R\ufffdZa&\ufffdV\u0004\u000b\ufffd\u001b_\u0004cq\ufffd\ufffd\u0016\ufffd3z\ufffdts\u001a\ufffd\ufffd\ufffd\ufffdj\ufffd\ufffd\ufffd\ufffd#\ufffd)：invalid character '\\x03' looking for beginning of value"}
[GVA]2021/02/05 - 16:54:07.467	error	D:/Colin/Projects/gva_dfzrf/server/api/jst_dfzrf/auth.go:38	手机登录出错!	{"err": "请重试"}
[GIN] 2021/02/05 - 16:54:07 | 200 |    582.4895ms |             ::1 | POST     "/dfzrf/wx-login-mobile"

==========wxLoginReq.EncryptedData
6TTKFNVOo0oS4wQlYbhPzCQt428WdP4JEqeZghIVho1bKcuWll8d/YLnoKj4yxZgwQ1GXIAs4cBGglDrC+/z7P1KnwukDrqBIkMvRuUWOHsMf6JpwNn3mIoK408FH817zy92jVHppP28JwvDGqRpIsmA2txuHY9Hx8lX9dEYVIASoIz39ryOnYM9jn7zbxl8gacVyK4wRyhjlF2Ebc4wSA==
string

==========wxLoginReq.Iv
EftLVE09l+RCFXb8mfTr8Q==
string

==========sessionRsp.SessionKey
ki65GuRX8eTisqPNenmWKg==
string
DecryptOpenDataToStruct:
{PhoneNumber:13913959731 PurePhoneNumber:13913959731 CountryCode:86 Watermark:0xc00106dce0}
[GIN] 2021/02/05 - 16:54:10 | 500 |    283.6582ms |             ::1 | POST     "/dfzrf/wx-login-mobile"

==========wxLoginReq.EncryptedData
5YadpWSFvW+RoDlmT1n1OSWQQp/VU+EdjYILNsWdhLotQWRqtzcAFFz+BWqraFfB+TOd0rdMG5446o7cwx4uDI3hPVB5/26EflzShDsy27FYcyvjOGx2r6vH0gPJ14xEQ6TfmVn2qv3eH8mMf9GCo1Yw/asv22GLTdw7AKj0GK4iNq7qX/9mQ+7ROyBCCFH3MhubtzfVqUu1peMbPwIQ8w==
string

==========wxLoginReq.Iv
da91o6+JK1mPr8pAjICaLA==
string

==========sessionRsp.SessionKey
ki65GuRX8eTisqPNenmWKg==
string
DecryptOpenDataToStruct:
{PhoneNumber:13913959731 PurePhoneNumber:13913959731 CountryCode:86 Watermark:0xc00130b240}
[GIN] 2021/02/05 - 16:54:13 | 500 |    299.0187ms |             ::1 | POST     "/dfzrf/wx-login-mobile"


==========wxLoginReq.EncryptedData
h7VVjdAXc65qTNCRpFzkEhwl/N5GUbc0x0GrrvKMtugM5cou6OX0DTD1Skz2VaKo6x3PDFvjum/XhaRuiZeZ4Pgywv4T5XsUG/UAyIm5aYFQ6YB7hjf+zDG+PlVoc/AP01ES9F4dK4QJx+1u3aEgfMxkCOHip2CNVhDlXlwoFRNlF8bbLNd17mWw25aRX06GeCwHBm/ImdFB8ekbnBKVYQ==
string

==========wxLoginReq.Iv
vjT7T//xxp1xH2oUpbYwXA==
string

==========sessionRsp.SessionKey
ki65GuRX8eTisqPNenmWKg==
string
DecryptOpenDataToStruct:
{PhoneNumber:13913959731 PurePhoneNumber:13913959731 CountryCode:86 Watermark:0xc0029162e0}
[GIN] 2021/02/05 - 16:54:15 | 500 |    217.3608ms |             ::1 | POST     "/dfzrf/wx-login-mobile"

**Comment by wziww** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/signature.html#method-decode
「会话密钥 session_key 有效性」
先按照官方文档确认下你的数据有没有问题吧

**Comment by lujscn** [comment]
好的谢谢

**Comment by wziww** [comment]
没问题的话就关掉吧

**Comment by lujscn** [comment]
暂时还没有搞定，我先关掉，谢谢，给您添麻烦了
