### ISSUE TITLE
should not using global mu for BodyMap

### ISSUE THREAD

**Issue by elvizlai** [iGoogle-ink/gopay#104]
https://github.com/iGoogle-ink/gopay/blob/fae2c5acb29e99cc8ebc7a38c97d3e660f3da564/body_map.go#L15

Why sharing global lock for BodyMap method.

The behavior is really strange.

For method Set, Get, it used mu, but for Reset, JsonBody, no lock are used.

In reality for this payment input request, no one read and write BodyMap in parallels.

**Comment by iGoogle-ink** [comment]
嗯，确实，之前写的，后来也没细看，暂时也不影响，有空改一下，谢谢

**Comment by iGoogle-ink** [comment]
还有就是，BodyMap 不一定只是用于支付参数，也可以作为一个map库用于其他场景
