### ISSUE TITLE
单笔转账接口报错

### ISSUE THREAD

**Issue by saxon134** [iGoogle-ink/gopay#108]
**接口名：**
client.FundTransUniTransfer
**描述：**
之前用的是gopay是v1.5.20，使用的是普通签名方式；
升级到v1.5.29，采用公钥证书签名方式，一直报签名失败。
证书文件都弄好了~
**错误信息：**
{"code":"40002","msg":"Invalid Arguments","sub_code":"isv.invalid-signature","sub_msg":"验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配，网关生成的验签字符串为：alipay_root_cert_sn=xxx&amp;app_auth_token=xxx
 
有木有谁遇到这个问题呀？有何解法？

**Comment by saxon134** [comment]
最终了解下来是因为，三方模式，已经不支持转账接口了。

**Comment by bennya8** [comment]
@saxon134 我也遇到这个问题，请问最终是怎解决？
