### ISSUE TITLE
微信v3中获取微信平台证书响应code问题

### ISSUE THREAD

**Issue by drrrMikado** [iGoogle-ink/gopay#110]
微信v3中获取微信平台证书响应（PlatformCertRsp）中的`Code`采用的是`res.StatusCode`（正常为200），这个code值跟其他响应（例如：PrepayRsp）中的`Code`（正常为 `0`，也就是`Success`常量）是不一致的。
这是设计如此吗？
代码位置：
PlatformCertRsp：
https://github.com/iGoogle-ink/gopay/blob/284974b56dd877fedd3bb72a8ed53fd2ceb82130/wechat/v3/cert.go#L35
PrepayRsp：
https://github.com/iGoogle-ink/gopay/blob/284974b56dd877fedd3bb72a8ed53fd2ceb82130/wechat/v3/pay_combine_api.go#L33

**Comment by drrrMikado** [comment]
应该是个错误，我看Test中判断都是用`Success`，代码：
https://github.com/iGoogle-ink/gopay/blob/284974b56dd877fedd3bb72a8ed53fd2ceb82130/wechat/v3/client_test.go#L46-L59

**Comment by iGoogle-ink** [comment]
ok
