### ISSUE TITLE
微信支付通知签名认证错误

### ISSUE THREAD

**Issue by godLei6** [iGoogle-ink/gopay#112]
在函数V3VerifySign中的x509.ParseCertificate报错,错误如下:
s:\"x509.ParseCertificate：asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false

**Comment by iGoogle-ink** [comment]
验签如果报错了，那就是验签失败了，检查一下验签用的微信平台公钥吧
