### ISSUE TITLE
企业付款到银行卡接口的问题

### ISSUE THREAD

**Issue by chenlixiang0430** [iGoogle-ink/gopay#127]
1. wechat/merchant_test.go，企业打款到银行卡示例代码中加密银行卡号和开户人使用的加密方法不对，示例中使用xrsa.RsaEncryptDataV2()，应使用xrsa.RsaEncryptOAEPData()，且加密后应进行base64编码。
2. pkg/xrsa/rsa_encrypt.go，xrsa.RsaEncryptDataV2()、xrsa.RsaEncryptOAEPData()方法pkcs1公钥加密出错，方法中解析pkcs1公钥使用了x509.ParsePKIXPublicKey()，解析pkcs1应使用x509.ParsePKCS1PublicKey()。
希望可以修复一下，避免后面有人踩坑。

**Comment by iGoogle-ink** [comment]
@chenlixiang0430 
wechat/merchant_test.go 里的示例未真实测试过，没有测试条件，感谢反馈，另外请问，xrsa.RsaEncryptOAEPData() 里 label 填写 nil 吗？
感谢反馈问题，立马修复

**Comment by iGoogle-ink** [comment]
对于你第二个问题，我测试过了， 用 ParsePKCS1PublicKey() 的话，会报错，提示使用 ParsePKIXPublicKey()
`x509: failed to parse public key (use ParsePKIXPublicKey instead for this key format)`

**Comment by chenlixiang0430** [comment]
你是不是用了pkcs8格式的秘钥测试，我刚刚又测了一下，用ParsePKCS1PublicKey()没有问题的，刚刚写的功能也是改成ParsePKCS1PublicKey()&nbsp;才成功的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iGoogle-ink/gopay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 下午2:40
***@***.***&gt;;
抄送:&nbsp;"PLAY   ***@***.******@***.***&gt;;
主题:&nbsp;Re: [iGoogle-ink/gopay] 企业付款到银行卡接口的问题 (#127)





 
对于你第二个问题，我测试过了， 用 ParsePKCS1PublicKey() 的话，会报错，提示使用 ParsePKIXPublicKey()
 x509: failed to parse public key (use ParsePKIXPublicKey instead for this key format)

**Comment by chenlixiang0430** [comment]
是的，xrsa.RsaEncryptOAEPData() 里 label 填写 nil就好。

**Comment by iGoogle-ink** [comment]
> 你是不是用了pkcs8格式的秘钥测试，我刚刚又测了一下，用ParsePKCS1PublicKey()没有问题的，刚刚写的功能也是改成ParsePKCS1PublicKey()&nbsp;才成功的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "iGoogle-ink/gopay" ***@***.***&gt;; 发送时间:&nbsp;2021年3月24日(星期三) 下午2:40 ***@***.***&gt;; 抄送:&nbsp;"PLAY ***@***.******@***.***&gt;; 主题:&nbsp;Re: [iGoogle-ink/gopay] 企业付款到银行卡接口的问题 (#127) 对于你第二个问题，我测试过了， 用 ParsePKCS1PublicKey() 的话，会报错，提示使用 ParsePKIXPublicKey() x509: failed to parse public key (use ParsePKIXPublicKey instead for this key format) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

确实是，我用了PKCS8 的，转换成PKCS1后，成功了，已经修复了，跟另外的新接口一起发车release tag 了
