### ISSUE TITLE
希望增加一个外部调用的签名方法

### ISSUE THREAD

**Issue by larry-dev** [iGoogle-ink/gopay#129]
如：
![image](https://user-images.githubusercontent.com/18585750/113284341-13790e00-931c-11eb-9cc9-c33cd79f3d56.png)

原因是：
![image](https://user-images.githubusercontent.com/18585750/113284432-33103680-931c-11eb-8856-e0c100e1700c.png)

经过多次与支付宝沟通确定下来此时不需要进行接口请求只需要签名就可以

**Comment by larry-dev** [comment]
也就是sdkExecute就是只做了签名的事情，其它什么都没有做

**Comment by larry-dev** [comment]
@iGoogle-ink

**Comment by larry-dev** [comment]
#131 已经增加了PR麻烦确认一下

**Comment by larry-dev** [comment]
@iGoogle-ink 是否可以发布一个版本，我这边无法更新最新版本

**Comment by iGoogle-ink** [comment]
@larry-dev
 好的，我看看

**Comment by larry-dev** [comment]
感谢，看到已经发布了
