### ISSUE TITLE
支付宝App支付后回调通知验证签名

### ISSUE THREAD

**Issue by visualzhang** [iGoogle-ink/gopay#13]
现在VerifyAliPaySign都是直接用AliPayPublicKey字符串来做验签的，没有通过crt文件来验签。
crt文件读出来的SN字符怎么来做验签？您有空加一下？我自己也看看怎么搞。

**Comment by iGoogle-ink** [comment]
好的，有空看一下，如果你弄好了，提个PR吧

**Comment by iGoogle-ink** [comment]
@visualzhang 好的，这两天的就处理一下

**Comment by iGoogle-ink** [comment]
https://docs.open.alipay.com/200/106120，只有同步验签，支持SN，异步验签和原来一样

**Comment by visualzhang** [comment]
最近忙别的，还没空看呢。我开始是用了VerifyAliPaySign来验证那个回调通知的数据，结果没通过。我对秘钥这块又不熟悉，就没有继续深入去看。
