### ISSUE TITLE
[微信支付]sdk同时支持Native支付与JSAPI支付时，签名异常

### ISSUE THREAD

**Issue by imloama** [iGoogle-ink/gopay#132]
我们的项目比较简单，支付部分同时支持Native支付与JSAPI支付，因为`ClientV3`只有一个`Appid`，默认配置的是`App应用`的appid。
主要不同点有两个，
- 调用`统一下单`api时，指定`appid=公众号appid`可以通过
- 在进行JSAPI的签名时，无法通过参数修改`appid`，[v3/sign.go](https://github.com/iGoogle-ink/gopay/blob/0ad1c27f2b695164a83cabce73ce850f9db574eb/wechat/v3/sign.go#L50)的，参与签名的`appid`还是之前配置的`App应用`的appid，导致JSAPI的签名校验失败

解决方案
- 直接修改`ClientV3`的`Appid`，调用完从参数后再改回来，是否可行，不会影响其它的接口，目前看的情况是不会影响
- 自定义`PaySignOfJSAPI`，从而自己修改，但`rsaSign`无法外部访问，导致要复制调整的代码有点多，但不会影响其它的接口

我们目前采用的第二种方案，暂时没有问题

**Comment by wziww** [comment]
多个的话你使用多个实例好了

**Comment by imloama** [comment]
> 多个的话你使用多个实例好了

嗯，也可以的。
