### ISSUE TITLE
pem.Decode

### ISSUE THREAD

**Issue by iwalkerr** [iGoogle-ink/gopay#136]
微信小程序支付，读取私钥 apiclient_key.pem 读取后的内容，pem.Decode([]byte(pkContent))解析失败。具体看下报错内容

![image](https://user-images.githubusercontent.com/43042929/118750671-6ab64c00-b892-11eb-909b-bf1f2d18530f.png)

pem内容：
![image](https://user-images.githubusercontent.com/43042929/118750952-1495d880-b893-11eb-8603-b888fd3abce5.png)

**Comment by iGoogle-ink** [comment]
你确定你读出来了？确定传的参数是证书字符串？要是这么简单的问题都有，不早就有人反馈了吗？我觉得你可以再试试，直接把证书字符串，写入到代码里，然后传进去

**Comment by iwalkerr** [comment]
> 你确定你对准来了？确定传的参数是证书字符串？要是这么简单的问题都有，不早就有人反馈了吗？我觉得你可以再试试，直接把证书字符串，写入到代码里，然后传

**Comment by iwalkerr** [comment]
> 你确定你读出来了？确定传的参数是证书字符串？要是这么简单的问题都有，不早就有人反馈了吗？我觉得你可以再试试，直接把证书字符串，写入到代码里，然后传进去

我用代码读取证书文件，然后转成[]byte就好了。谢谢楼主，可能是我复制字符串，\t\n\r这些空格字符导致的

**Comment by meihuasannong** [comment]
> > 你确定你读出来了？确定传的参数是证书字符串？要是这么简单的问题都有，不早就有人反馈了吗？我觉得你可以再试试，直接把证书字符串，写入到代码里，然后传进去
> 
> 我用代码读取证书文件，然后转成[]byte就好了。谢谢楼主，可能是我复制字符串，\t\n\r这些空格字符导致的

我也碰到了同样的问题，请问怎么解决的？
