### ISSUE TITLE
支付宝授权获取用户信息,  sign报错

### ISSUE THREAD

**Issue by swat521** [iGoogle-ink/gopay#22]
body := make(gopay.BodyMap)
	body.Set("grant_type", "authorization_code")
	body.Set("code", authCode)
	//发起请求
	aliRsp, err := client.SystemOauthToken(body)
	if err != nil {
		fmt.Println("err:", err)
	}
	fmt.Println(aliRsp)
通过其它sdk 测试参数没有错误,生成签名的时候报错
报错
err: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5

**Comment by iGoogle-ink** [comment]
OK，谢谢反应
