### ISSUE TITLE
支付宝支付回调验签，验证失败，报错信息：crypto/rsa: verification error

### ISSUE THREAD

**Issue by daimengxiaozhi** [iGoogle-ink/gopay#34]
支付宝支付回调验签，验证失败，报错信息：crypto/rsa: verification error，出现三次。偶现。发现一个客户 两个订单都出现了这种情况。

**Comment by daimengxiaozhi** [comment]
发现三次都有一个共同点，有优惠券
voucher_detail_list  参数 : [{"name":"2元实体店通用红包","type":"ALIPAY_CASH_VOUCHER","amount":"0.10"}]

**Comment by iGoogle-ink** [comment]
好的，可能有部分参数缺失，我看一下

**Comment by iGoogle-ink** [comment]
能说一下，具体是哪个支付接口吗？  alipay.trade.pay ？

**Comment by daimengxiaozhi** [comment]
> 能说一下，具体是哪个支付接口吗？ alipay.trade.pay ？

alipay.VerifySign(config.Value, notifyReq)

**Comment by iGoogle-ink** [comment]
我的意思是，异步通知验签失败，对吗？只要是带voucher_detail_list 这个参数的？

**Comment by daimengxiaozhi** [comment]
> 我的意思是，异步通知验签失败，对吗？只要是带voucher_detail_list 这个参数的？
是的，它们的共同点就是带voucher_detail_list  其它为null

**Comment by iGoogle-ink** [comment]
我晓得问题了，这个  voucher_detail_list  参数会根据不同的支付接口，返回来的参数不一样，导致验签有问题

**Comment by daimengxiaozhi** [comment]
> 我晓得问题了，这个 voucher_detail_list 参数会根据不同的支付接口，返回来的参数不一样，导致验签有问题
好的  什么时候能修复呢 ？

**Comment by iGoogle-ink** [comment]
这个需要改一下实现方法了，要把结构体换成Map了，不然没法确定不同的接口返回的参数，今天我就处理

**Comment by daimengxiaozhi** [comment]
> 这个需要改一下实现方法了，要把结构体换成Map了，不然没法确定不同的接口返回的参数，今天我就处理

好的，谢谢啦

**Comment by iGoogle-ink** [comment]
异步通知里的具体json信息，你方便提供一份吗？我看一下，因为支付宝的文档，实在是坑人，文档上的，跟实际的不一样

**Comment by iGoogle-ink** [comment]
alipay.ParseNotifyResultToBodyMap() => 解析支付宝支付异步通知的参数到BodyMap
你试一下这个方法，解析验签是否可以

**Comment by daimengxiaozhi** [comment]
具体的json 信息估计没有，这是我从数据库 导出的
{
            "notify_time": "2020-04-24 13:14:20",
            "notify_type": "trade_status_sync",
            "notify_id": "xxx",
            "app_id": "xxx",
            "charset": "utf-8",
            "version": "1.0",
            "sign_type": "RSA2",
            "sign": "bphqBmVFdYUMHA59yxqZxDwV2qJ3X0IMRt0uBYH4VYPnSn+2yTGjAvdDb8unbEKmPEQKiv2P3khkriJIvGGBv6IRwheEmkh0rMl8zT7sQMcggXWRMjrkhIKQD64aOuXfEqx+BT6GrP+w/CxIrTZeK5G9/a5Oc7TDOS6KBhwhIRgoNRdyKIAO5k8zDY56SK5e0EJ7GX/HA9wK9I2c3yb0ZruvtrsAcBaGfkwp4IuHQC4Zz1xwqLE9rh+yINMgy9t",
            "auth_app_id": "xxxx",
            "trade_no": "xxx",
            "out_trade_no": "xxx",
            "out_biz_no": "",
            "buyer_id": "xxx",
            "buyer_logon_id": "xxx",
            "seller_id": "xxx",
            "seller_email": "xxxx",
            "trade_status": "TRADE_SUCCESS",
            "total_amount": "10.00",
            "receipt_amount": "10.00",
            "invoice_amount": "9.90",
            "buyer_pay_amount": "9.90",
            "point_amount": "0.00",
            "refund_fee": "",
            "subject": "xxxx-10.00",
            "body": "软件天卡-10.00",
            "gmt_create": "2020-04-24 13:14:18",
            "gmt_payment": "2020-04-24 13:14:19",
            "gmt_refund": "",
            "gmt_close": "",
            "fund_bill_list": "[{\"amount\":\"9.90\",\"fundChannel\":\"PCREDIT\"},{\"amount\":\"0.10\",\"fundChannel\":\"DISCOUNT\"}]",
            "passback_params": "",
            "voucher_detail_list": "[{\"name\":\"2元实体店通用红包\",\"type\":\"ALIPAY_CASH_VOUCHER\",\"amount\":\"0.10\"}]",
            "method": "",
            "timestamp": ""
        },
这个估计没有参考意义，我找下日志吧 。主要是不知道怎么重现 ，我用的花呗红包是正常的 ，不知道他这个红包是啥-。-

**Comment by daimengxiaozhi** [comment]
没找到日志  我把日志加上了，再看看吧~

**Comment by iGoogle-ink** [comment]
修复完了，废弃了Parse请求参数到结构体的那个方法，1.5.9 ，推荐解析到 BodyMap 里，然后再验签

**Comment by iGoogle-ink** [comment]
v1.5.9 release 了，看一下 release_note 吧： https://github.com/iGoogle-ink/gopay/blob/master/release_note.txt

**Comment by daimengxiaozhi** [comment]
> v1.5.9 release 了，看一下 release_note 吧： https://github.com/iGoogle-ink/gopay/blob/master/release_note.txt

好的，感谢！
