### ISSUE TITLE
在设置微信交易类型的时候好像有点问题

### ISSUE THREAD

**Issue by cjphaha** [iGoogle-ink/gopay#37]
bm.Set("trade_type", gopay.TradeType_Mini)

**Comment by cjphaha** [comment]
就是里面找不到TradeType_Mini这个参数，请问这个该怎么解决呀

**Comment by cjphaha** [comment]
显示Unresolved reference 'TradeType_Mini‘

**Comment by iGoogle-ink** [comment]
wechat.TradeType_Mini

**Comment by cjphaha** [comment]
好嘞谢谢
