### ISSUE TITLE
支付宝code获取用户userid报错

### ISSUE THREAD

**Issue by JayenLee** [iGoogle-ink/gopay#38]
cannot unmarshal number into Go struct field oauthTokenInfo.alipay_system_oauth_token_response.expires_in of type string

**Comment by JayenLee** [comment]
用是这个方法 SystemOauthToken

**Comment by iGoogle-ink** [comment]
@JayenLee
已经有人修复了，升级一下版本吧

**Comment by JayenLee** [comment]
是哪版本，我目前用是10的，是否今天有最新的版本？

**Comment by iGoogle-ink** [comment]
@JayenLee    应该是 1.5.11 了

**Comment by JayenLee** [comment]
新的修复能否改改下？
