### ISSUE TITLE
查询企业付款好像没发现有啊

### ISSUE THREAD

**Issue by siyue543241338** [iGoogle-ink/gopay#42]
[https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3](url)
企业给个人付款之后的查询接口没找到,还有App登录是GetAppLoginAccessToken 这个接口,但是没发现有App获取用户信息的

不知道能加上吗

**Comment by iGoogle-ink** [comment]
> [https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3](url)
> 企业给个人付款之后的查询接口没找到,还有App登录是GetAppLoginAccessToken 这个接口,但是没发现有App获取用户信息的
> 
> 不知道能加上吗

有时间了，可以加上，稍等吧

**Comment by iGoogle-ink** [comment]
@siyue543241338 
方法已增加，测试一下吧

**Comment by siyue543241338** [comment]
@iGoogle-ink 可以了多谢
