### ISSUE TITLE
微信服务商模式支付验签失败

### ISSUE THREAD

**Issue by wailovet** [iGoogle-ink/gopay#45]
原因是NotifyRequest缺少
+ sub_appid
+ sub_is_subscribe
+ sub_mch_id
+ sub_openid

**Comment by iGoogle-ink** [comment]
@wailovet 
好的，谢谢，之前在做的时候，没有考虑服务商，只做的基本支付
推荐替换成 ParseNotifyToBodyMap() 方法

**Comment by wailovet** [comment]
@iGoogle-ink 
辛苦大佬了,后面用成ParseNotifyToBodyMap就解决了,防止其他人也遇到同样的问题就说一下
