### ISSUE TITLE
异步回调的验签一直报错

### ISSUE THREAD

**Issue by zhuying1027** [iGoogle-ink/gopay#46]
verify sign error: crypto/rsa: verification error

**Comment by birdycn** [comment]
请问您是怎么解决的，我也遇到这个问题了

**Comment by zhuying1027** [comment]
你是用的证书的吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "birdycn"<notifications@github.com&gt;; 
发送时间: 2020年7月19日(星期天) 凌晨3:42
收件人: "iGoogle-ink/gopay"<gopay@noreply.github.com&gt;; 
抄送: "天道"<962161252@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [iGoogle-ink/gopay] 异步回调的验签一直报错 (#46)





 
请问您是怎么解决的，我也遇到这个问题了
