### ISSUE TITLE
微信支付退款Refund()怎么要三个证书啊？

### ISSUE THREAD

**Issue by Rebellioncry** [iGoogle-ink/gopay#49]
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
官方文档只有php需要两个证书，其他语言只要.p12格式的证书就行了，这要怎么做？

**Comment by iGoogle-ink** [comment]
@Rebellioncry 
你可以尝试，只传一个试试？

**Comment by Rebellioncry** [comment]
> @Rebellioncry
> 你可以尝试，只传一个试试？

我看了你写的源码，要判断三个路径，“注意：如已使用client.AddCertFilePath()添加过证书，参数certFilePath、keyFilePath、pkcs12FilePath全传空字符串 ""，否则，3证书Path均不可空”，有checkCertFilePath()判断是否有传值，所以应该是不能只传一个的

**Comment by yicll** [comment]
同问

**Comment by Rebellioncry** [comment]
> 同问

三个都传吧，就当作是php一样的方式吧

**Comment by li-keli** [comment]
我测试发现`client.AddCertFilePath()`方法没有生效；
目前只能在`client.Refund()`中传入证书地址才有效； @iGoogle-ink

**Comment by iGoogle-ink** [comment]
新版本已经有人解决了该问题了
