### ISSUE TITLE
获取参数签名出错 getRsaSign()函数

### ISSUE THREAD

**Issue by Ravlyon** [iGoogle-ink/gopay#5]
asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType: 0 timeType: 0 set: false omitEmpty:false} @5asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType: 0 timeType: 0 set: false omitEmpty:false} @5

**Comment by Ravlyon** [comment]
一直找不到原因之后试了一下别的sdk，发现我的公钥私钥是没有错误的

**Comment by iGoogle-ink** [comment]
仔细看看文档，我这是没有测出问题的，还有，最近更新，添加了公钥方式，这个是没有测试过的
