### ISSUE TITLE
微信支付分账实现

### ISSUE THREAD

**Issue by fxk2006** [iGoogle-ink/gopay#52]
大大神，能否加上微信分账功能
https://pay.weixin.qq.com/wiki/doc/api/allocation.php?chapter=26_1

**Comment by iGoogle-ink** [comment]
@fxk2006 
好的，这周找时间加上

**Comment by fxk2006** [comment]
> @fxk2006
> 好的，这周找时间加上

已实现，提交pr给你了，请审核

**Comment by iGoogle-ink** [comment]
@fxk2006 
大佬，你的PR，提了一些 discussion ，稍微调整一下吧

**Comment by fxk2006** [comment]
调整了，请大佬审核
