### ISSUE TITLE
所有需要certfilepath的地方希望扩展一个方法，直接传入二进制数组

### ISSUE THREAD

**Issue by shushenghong** [iGoogle-ink/gopay#6]
很多时候证书不一定是存在硬盘的某个文件里，不方便扩展，建议支持二进制流直接传入，譬如微信的退款，不要固定本地读取文件
![image](https://user-images.githubusercontent.com/3275714/66307994-83c9ed80-e938-11e9-9dd2-8032a94440a6.png)

可参考tls的LoadX509KeyPair和X509KeyPair
![image](https://user-images.githubusercontent.com/3275714/66307948-62690180-e938-11e9-967c-17ddddf6c769.png)

**Comment by iGoogle-ink** [comment]
好的，谢谢
