### ISSUE TITLE
ProfitSharingQuery接口有问题，https://api.mch.weixin.qq.com/pay/profitsharingquery接口参数不带appid，但是Client.doProdPost里添加了bm.Set("appid", w.AppId)，导致签名校验失败！

### ISSUE THREAD

**Issue by zhangbo0724** [iGoogle-ink/gopay#68]

**Comment by iGoogle-ink** [comment]
@zhangbo0724 
好的，谢谢反馈，我去看一下

**Comment by iGoogle-ink** [comment]
@zhangbo0724 
先暂时用这个 commit 的版本吧，6515a5b
我先不发新版本，等qq红包写完，一起发一个版本

**Comment by zhangbo0724** [comment]
ok,3ks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iGoogle-ink/gopay"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 中午11:09
收件人:&nbsp;"iGoogle-ink/gopay"<gopay@noreply.github.com&gt;;
抄送:&nbsp;"张波"<37738055@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [iGoogle-ink/gopay] ProfitSharingQuery接口有问题，https://api.mch.weixin.qq.com/pay/profitsharingquery接口参数不带appid，但是Client.doProdPost里添加了bm.Set("appid", w.AppId)，导致签名校验失败！ (#68)





 
@zhangbo0724
 先暂时用这个 commit 的版本吧，6515a5b
 我先不发新版本，等qq红包写完，一起发一个版本
