### ISSUE TITLE
ParseNotify,ParseNotifyToBodyMap报错 EOF

### ISSUE THREAD

**Issue by fxxxxxxxxxxx** [iGoogle-ink/gopay#69]
body中有数据，但ParseNotify会解析错误xml.NewDecoder.Decode：EOF，ParseNotifyToBodyMap则是xml.Unmarshal err

**Comment by iGoogle-ink** [comment]
@Bran2W 
确认一下，有没有做 http.Request.Body的复用，如果用一些主流web框架的话，不会出现这个问题，自己实现接口的话，注意Body复用的问题，原生的是用一次，就不再保留了。
