### ISSUE TITLE
微信签名算法需过滤空值

### ISSUE THREAD

**Issue by shushenghong** [iGoogle-ink/gopay#7]
![image](https://user-images.githubusercontent.com/3275714/66387135-ed5c0180-e9f5-11e9-9f87-c951849f50b9.png)
参考文档：
[微信签名算法](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=4_3)
```
签名生成的通用步骤如下：

第一步，设所有发送或者接收到的数据为集合M，将集合M内非空参数值的参数按照参数名ASCII码从小到大排序（字典序），使用URL键值对的格式（即key1=value1&key2=value2…）拼接成字符串stringA。

特别注意以下重要规则：

◆ 参数名ASCII码从小到大排序（字典序）；
◆ 如果参数的值为空不参与签名；
◆ 参数名区分大小写；
◆ 验证调用返回或微信主动通知签名时，传送的sign参数不参与签名，将生成的签名与该sign值作校验。
◆ 微信接口可能增加字段，验证签名时必须支持增加的扩展字段
第二步，在stringA最后拼接上key得到stringSignTemp字符串，并对stringSignTemp进行MD5运算，再将得到的字符串所有字符转换为大写，得到sign值signValue。
```

**Comment by iGoogle-ink** [comment]
谢谢了，确实需要对key值判空，有可能是空字符串

**Comment by Rbcum** [comment]
在调用微信接口返回，如果有些int类型的节点值为0，那么在VerifyWeChatSign时这些节点会丢失，导致验签失败，这个怎么解决好点？把int节点换成*int怎样？
