### ISSUE TITLE
微信付款成功验签，err = nil，但ok = false 是什么情况？

### ISSUE THREAD

**Issue by ysongyang** [iGoogle-ink/gopay#71]
notifyReq, err := wechat.ParseNotifyToBodyMap(ctx.Request)
// 验签操作
ok, err := wechat.VerifySign(apiKey, wechat.SignType_MD5, notifyReq)

log.Println(ok) // false
log.Println(err) // <nil>

这是什么操作？？？？？？

**Comment by wziww** [comment]
一个是 sdk 使用异常(error)，一个是 sdk 正常情况下验签的结果（true / false)

**Comment by iGoogle-ink** [comment]
@ysongyang 
可以看一下源码，error是业务处理 error，判断error不为空，再判断 ok 是否 为 true

**Comment by ysongyang** [comment]
问题已解决~~~
