### ISSUE TITLE
升级后报错

### ISSUE THREAD

**Issue by izuojian** [iGoogle-ink/gopay#78]
/root/go/pkg/mod/github.com/i!google-ink/gotil@v1.0.8-0.20200930171421-152bfb39873b/xlog/debug_logger.go:27:58: undefined: log.Lmsgprefix

**Comment by iGoogle-ink** [comment]
@izuojian 
好的，这个应该是你本地或者服务器 golang 版本低，不支持的原因，我兼容处理一下吧

**Comment by iGoogle-ink** [comment]
建议升级 golang 到 1.14+

**Comment by izuojian** [comment]
go版本 1.15+

**Comment by iGoogle-ink** [comment]
@izuojian 
已经修复了这个问题，1.5.22 版本已经支持到 go1.13 了
