### ISSUE TITLE
微信退款，证书参数时要怎么传递证书内容呢？

### ISSUE THREAD

**Issue by drrrMikado** [iGoogle-ink/gopay#84]
现在证书内容是接受文件路径，现在怎么接受文件内容？
另外，p12和 cert/key 这两个能二选一传递吗？

**Comment by stelin** [comment]
我也遇到这个问题了，希望尽快解决下

**Comment by iGoogle-ink** [comment]
了解了，证书内容传递，我测试过，证书好像必须全传，少传我测试的会失败

**Comment by JayenLee** [comment]
p12 证书在微信开发文档上面不是写了除了php外都可以直接使用这个，现在那两个证书都么有了，只有这个p12证书，正常应该不需要cert/key证书的，java上面已经不需要了这两个证书去开发了

**Comment by JayenLee** [comment]
tls.LoadX509KeyPair：tls: failed to find any PEM data in key input

我觉得应该是您这边用错库了，好像有一个专门的库pk12的然后用密码把pk12解析出来，你这边测试的应该是用ca证书而不是pk12证书，所以你感觉都要全部传入才能成功，但是微信现在都是用的pk12证书了

**Comment by JayenLee** [comment]
新增的内容能不能建一个新版本？

**Comment by iGoogle-ink** [comment]
> p12 证书在微信开发文档上面不是写了除了php外都可以直接使用这个，现在那两个证书都么有了，只有这个p12证书，正常应该不需要cert/key证书的，java上面已经不需要了这两个证书去开发了

楼上大佬已经解决了微信证书二选一的问题了
