### ISSUE TITLE
微信支付签名不一致问题

### ISSUE THREAD

**Issue by savico-swee** [iGoogle-ink/gopay#88]
在沙箱环境下用微信支付接口签名校验工具测得sign匹配不一致

**Comment by savico-swee** [comment]
// 从微信提供的接口获取：SandboxSignKey
func getSanBoxKey(mchId, nonceStr, apiKey, signType string) (key string, err error) {
	bm := make(gopay.BodyMap)
	bm.Set("mch_id", mchId)
	bm.Set("nonce_str", nonceStr)

	//沙箱环境：获取沙箱环境ApiKey
	if key, err = getSanBoxSignKey(mchId, nonceStr, getReleaseSign(apiKey, signType, bm)); err != nil {
		return
	}
	return
}


param.go文件是不是存在问题，调的是生产的sign:getReleaseSign

**Comment by savico-swee** [comment]
目前测试发现生产环境没有问题，沙箱环境存在问题~

**Comment by savico-swee** [comment]
沙箱验证签名失败，应该是微信沙箱环境不稳定

**Comment by iGoogle-ink** [comment]
@savico-swee  
是的，沙箱环境不稳定，一般测试还是推荐使用正式环境，1分钱测试法
