### ISSUE TITLE
微信支付分账client.ProfitSharing中的BodyMap里的receivers的写法

### ISSUE THREAD

**Issue by lujscn** [iGoogle-ink/gopay#98]
微信支付分账client.ProfitSharing中的BodyMap里的receivers的写法，可以给个示例吗？

尝试了几种写法，都是得到错误提示：can not transfer receivers to []BodyMap

谢谢了

**Comment by iGoogle-ink** [comment]
@lujscn  抱歉刚看到，我去修改一下这个地方的实现，此处合并的别人的PR, 没注意看，

**Comment by lujscn** [comment]
谢谢大佬

**Comment by iGoogle-ink** [comment]
@lujscn  master 代码已经发了，但是还没有 release 打tag

**Comment by lujscn** [comment]
太感谢大佬了，回头我试试

**Comment by iGoogle-ink** [comment]
@lujscn  你回复好快啊，我刚发了 release 了，那个 slice 的receivers写法，我放在 `wechat/merchant_test.go` 文件里的 `Test_ProfitSharing` 方法了

**Comment by lujscn** [comment]
好的好的
