### ISSUE TITLE
微信支付

### ISSUE THREAD

**Issue by pyting** [iGoogle-ink/gopay#99]
`func TestGetPlatformCerts(t *testing.T) {
	certs, err := client.GetPlatformCerts()
	if err != nil {
		xlog.Error(err)
		return
	}
	if certs.Code == **Success** {
		for _, v := range certs.Certs {
			xlog.Debug("cert:", v)
		}
		return
	}
	xlog.Errorf("certs:%s", certs.Error)
}`

测试发现certs.Code = 200代表正常，但目前wechat.Success = 0

**Comment by iGoogle-ink** [comment]
@pyting  好的，我查看一下是不是有这个问题

**Comment by iGoogle-ink** [comment]
@pyting  故意这么设计的，Success = 0 ，代表成功
请参考  `wechat/v3/client_test.go` 的test方法：TestGetPlatformCerts()
